spring.application.name=backend
# Configuración temporal para que arranque sin conectar a MySQL real todavía
spring.datasource.url=jdbc:mysql://localhost:3306/jamonbooking_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=sergio1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
